/**
 * Turn the client's Logo2023rgi.pdf (converted to SVG by pdftocairo) into a clean,
 * transparent, tightly-cropped logo asset for the site.
 *
 *  - drops the black backdrop rectangle (the PDF is white-on-black artwork)
 *  - keeps only the white logo paths, repainted as `currentColor` so the same file
 *    works white on the dark header and dark on a light surface
 *  - crops the viewBox to the ink, so there is no invisible padding to fight in CSS
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const WEB = `${ROOT}/apps/web`;
const PDF = `${ROOT}/Logo2023rgi.pdf`;
const RAW = `${ROOT}/scripts/.logo-raw.svg`;

// pdftocairo (poppler) turns the vector PDF into SVG without rasterising it.
execFileSync('pdftocairo', ['-svg', PDF, RAW]);
mkdirSync(`${WEB}/src/components/brand`, { recursive: true });
const raw = readFileSync(RAW, 'utf8');

// Every drawing instruction in a pdftocairo SVG is a <path .../> element.
const paths = [...raw.matchAll(/<path\b[^>]*\/>/g)].map((m) => m[0]);
const isWhite = (p) => /fill="rgb\(100%,\s*100%,\s*100%\)"/.test(p);
const white = paths.filter((p) => isWhite(p) && !/clip-rule/.test(p));

/**
 * Approximate bbox of a path from the numbers in its `d`. Bezier control points bound
 * the curve, so this over-estimates slightly — plenty to spot an outlier.
 */
function roughBox(p) {
  const d = p.match(/\sd="([^"]+)"/)?.[1] ?? '';
  const n = d.match(/-?\d+(?:\.\d+)?/g)?.map(Number) ?? [];
  const xs = n.filter((_, i) => i % 2 === 0);
  const ys = n.filter((_, i) => i % 2 === 1);
  if (!xs.length || !ys.length) return null;
  return { y0: Math.min(...ys), y1: Math.max(...ys) };
}

// The artwork sits inside the PDF's black backdrop square; pdftocairo also emits a stray
// speck near the bottom of the page. Keep only paths inside the artwork band.
const boxes = white.map(roughBox);
const LIMIT = 4500; // the backdrop square is 4500 units tall
const inArt = white.filter((p, i) => boxes[i] && boxes[i].y0 < LIMIT);
const dropped = white.length - inArt.length;
white.length = 0;
white.push(...inArt);

console.log(
  `paths total=${paths.length} white=${inArt.length + dropped} ` +
    `kept=${inArt.length} dropped-as-stray=${dropped}`,
);

// Strip per-path fill/opacity so the group's currentColor wins.
const bodies = white.map((p) =>
  p
    .replace(/fill="rgb\([^)]*\)"/, '')
    .replace(/fill-opacity="[^"]*"/, '')
    .replace(/\s+/g, ' '),
);

const vb = raw.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);
const [, , vbW, vbH] = vb;

const build = (viewBox, color) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">` +
  `<g fill="${color}">${bodies.join('')}</g></svg>`;

// --- find the ink bounding box by rasterising the white-only artwork ---------
const PROBE = 2000; // px wide probe render
const probeSvg = build(`0 0 ${vbW} ${vbH}`, '#000');
const probe = sharp(Buffer.from(probeSvg), { density: 96 }).resize({ width: PROBE });
const { data, info } = await probe
  .ensureAlpha()
  .raw()
  .toBuffer({ resolveWithObject: true });

let minX = info.width, minY = info.height, maxX = -1, maxY = -1;
for (let y = 0; y < info.height; y++) {
  for (let x = 0; x < info.width; x++) {
    if (data[(y * info.width + x) * info.channels + 3] > 8) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
}
const scale = vbW / info.width; // user units per probe pixel
const pad = 0; // crop tight; spacing is a CSS concern
const bx = minX * scale - pad;
const by = minY * scale - pad;
const bw = (maxX - minX + 1) * scale + pad * 2;
const bh = (maxY - minY + 1) * scale + pad * 2;

console.log(
  `ink bbox: x=${bx.toFixed(1)} y=${by.toFixed(1)} w=${bw.toFixed(1)} h=${bh.toFixed(1)} ` +
    `ratio=${(bw / bh).toFixed(3)}`,
);

const viewBox = `${bx.toFixed(2)} ${by.toFixed(2)} ${bw.toFixed(2)} ${bh.toFixed(2)}`;

// 1. Standalone file — Open Graph, e-mail, anything that needs a URL.
const cropped = build(viewBox, 'currentColor');
writeFileSync(`${WEB}/public/logo-rgi.svg`, cropped);
console.log(`wrote public/logo-rgi.svg (${cropped.length} bytes)`);

// 2. The React component the UI actually renders. Inline beats <img> here: it inherits
//    `currentColor`, so one component is white on the dark header and dark on a light
//    surface, and it costs no extra request.
const jsx = `/**
 * The Rgi Service logo — the client's own artwork (Logo2023rgi.pdf), traced to paths.
 *
 * GENERATED by \`scripts/build-logo.mjs\`. Do not hand-edit: re-run the script instead.
 *
 * The mark carries the "RGI" wordmark only, exactly as the shop sign does; the word
 * "Service" is set as live text beside it by <Logo />, so it stays selectable, translatable
 * and readable to a screen reader.
 */
export function LogoMark({
  className,
  style,
}: {
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <svg
      viewBox="${viewBox}"
      className={className}
      style={style}
      role="img"
      aria-label="RGI"
      fill="currentColor"
    >
      ${monoPathsForJsx(bodies)}
    </svg>
  );
}
`;
writeFileSync(`${WEB}/src/components/brand/LogoMark.tsx`, jsx);
console.log(`wrote src/components/brand/LogoMark.tsx`);

function monoPathsForJsx(list) {
  return list
    .map((p) =>
      p
        .replace(/fill-rule="([^"]*)"/g, 'fillRule="$1"')
        .replace(/clip-rule="([^"]*)"/g, 'clipRule="$1"')
        .replace(/\s+/g, ' ')
        .trim(),
    )
    .join('\n      ');
}

// 3. Favicon + apple touch icon, rendered from the same paths on the brand background.
const ICON_BG = '#0B0B12'; // DESIGN_SYSTEM.md --bg
async function icon(size, pad, out) {
  const inner = Math.round(size * (1 - pad * 2));
  // Give the SVG an explicit pixel size so the rasteriser renders straight to it —
  // a density high enough for this viewBox would blow sharp's pixel limit.
  const sized = build(viewBox, '#ffffff').replace(
    '<svg ',
    `<svg width="${inner * 4}" height="${Math.round((inner * 4 * bh) / bw)}" `,
  );
  const art = await sharp(Buffer.from(sized))
    .resize({ width: inner, fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
  await sharp({
    create: {
      width: size,
      height: size,
      channels: 4,
      background: ICON_BG,
    },
  })
    .composite([{ input: art, gravity: 'centre' }])
    .png()
    .toFile(out);
  console.log(`wrote ${out.split(/[\\/]/).pop()} (${size}px)`);
}
await icon(64, 0.06, `${WEB}/src/app/icon.png`);
await icon(180, 0.14, `${WEB}/src/app/apple-icon.png`);

/** Render the lockup to a PNG of a given width, white on transparent. */
async function lockupPng(width) {
  const sized = build(viewBox, '#ffffff').replace(
    '<svg ',
    `<svg width="${width}" height="${Math.round((width * bh) / bw)}" `,
  );
  return sharp(Buffer.from(sized)).png().toBuffer();
}

// 4. Organization logo for JSON-LD. Google's logo guidelines want a raster, not an SVG.
{
  const art = await lockupPng(1000);
  await sharp({
    create: { width: 1200, height: 630, channels: 4, background: ICON_BG },
  })
    .composite([{ input: art, gravity: 'centre' }])
    .png()
    .toFile(`${WEB}/public/logo-rgi.png`);
  console.log('wrote public/logo-rgi.png (1200x630)');
}

// 5. Open Graph share card — what a WhatsApp or Facebook link preview shows.
{
  const LW = 520; // logo width; the rest of the card is laid out under it
  const LH = Math.round((LW * bh) / bw);
  const LTOP = 132;
  const art = await lockupPng(LW);
  const svgText = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
    <defs>
      <linearGradient id="g" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%" stop-color="#7C3AED"/><stop offset="100%" stop-color="#22D3EE"/>
      </linearGradient>
    </defs>
    <!-- Mixed case, matching the on-site lockup. The rasteriser has no Orbitron, so this
         falls back to a system grotesque; it reads as the brand name, not as the logo. -->
    <text x="600" y="${LTOP + LH + 62}" text-anchor="middle"
          font-family="Segoe UI, Arial, sans-serif"
          font-size="46" font-weight="600" letter-spacing="2" fill="#E8E8F0">Service</text>
    <rect x="510" y="${LTOP + LH + 96}" width="180" height="3" rx="1.5" fill="url(#g)"/>
    <text x="600" y="${LTOP + LH + 160}" text-anchor="middle"
          font-family="Segoe UI, Arial, sans-serif"
          font-size="29" fill="#A5A5B8">PC Gamer · Composants · Configurateur PC · Maroc</text>
  </svg>`;
  await sharp({
    create: { width: 1200, height: 630, channels: 4, background: ICON_BG },
  })
    .composite([
      { input: art, top: LTOP, left: Math.round((1200 - LW) / 2) },
      { input: Buffer.from(svgText), top: 0, left: 0 },
    ])
    .png()
    .toFile(`${WEB}/public/og-default.png`);
  console.log('wrote public/og-default.png (1200x630)');
}
